'use client';

import { useState } from 'react';
import { Users, Download, Loader2, Check } from 'lucide-react';
import JSZip from 'jszip';
import * as MidiWriter from 'midi-writer-js';
import { MidiData } from '@/lib/types';
import { MidiConverter } from '@/lib/midiConverter';

interface BandArrangerProps {
  midiData: MidiData;
}

const bandInstruments = [
  { id: 'piano', name: 'Piano', icon: '🎹', range: 'A0–C8' },
  { id: 'guitar', name: 'Guitar', icon: '🎸', range: 'E2–E6' },
  { id: 'bass', name: 'Bass', icon: '🎸', range: 'E1–C5' },
  { id: 'drums', name: 'Drums', icon: '🥁', range: 'C2–C6' },
  { id: 'violin', name: 'Violin', icon: '🎻', range: 'G3–A7' },
  { id: 'cello', name: 'Cello', icon: '🎻', range: 'C2–C6' },
  { id: 'flute', name: 'Flute', icon: '🎵', range: 'C4–C7' },
  { id: 'trumpet', name: 'Trumpet', icon: '🎺', range: 'F#3–D6' },
  { id: 'saxophone', name: 'Saxophone', icon: '🎷', range: 'Db3–A5' },
];

const noteNames = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'];

// Helper function to get valid pitch string
const getValidPitch = (midiNumber: number): string => {
  const noteName = noteNames[midiNumber % 12];
  const octave = Math.floor(midiNumber / 12) - 1;
  return `${noteName}${octave}`;
};

export function BandArranger({ midiData }: BandArrangerProps) {
  const [selectedInstruments, setSelectedInstruments] = useState<string[]>(['piano', 'bass']);
  const [isGenerating, setIsGenerating] = useState(false);

  const generateMidiTrack = (notes: any[], tempo: number) => {
    const track = new MidiWriter.Track();
    track.setTempo(tempo);
    track.setTimeSignature(4, 4);
    
    notes.forEach(note => {
      const pitchString = getValidPitch(note.pitch);
      // Use type assertion to satisfy MidiWriter
      track.addEvent(new MidiWriter.NoteEvent({
        pitch: [pitchString as any],
        duration: '4',
        velocity: note.velocity
      }));
    });
    
    const writer = new MidiWriter.Writer([track]);
    return writer.dataUri();
  };

  const generateParts = async () => {
    setIsGenerating(true);
    try {
      const zip = new JSZip();
      
      for (const instrument of selectedInstruments) {
        const instrumentData = bandInstruments.find(i => i.id === instrument);
        const convertedData = await MidiConverter.convertInstrument(midiData, instrument);
        
        // Generate HTML part sheet
        const htmlContent = `<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: 'Inter', sans-serif; background: #05080F; color: #EEF2FF; padding: 40px; }
    .header { border-bottom: 2px solid #C9A84C; margin-bottom: 30px; padding-bottom: 20px; }
    .title { font-size: 32px; font-weight: bold; color: #C9A84C; margin: 0; }
    .subtitle { color: #EEF2FF66; margin-top: 8px; }
    .info-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 16px; margin-bottom: 30px; }
    .info-card { background: #0A0F1A; border: 1px solid #C9A84C20; border-radius: 12px; padding: 16px; }
    .info-label { font-size: 12px; text-transform: uppercase; letter-spacing: 1px; color: #C9A84C; margin-bottom: 8px; }
    .info-value { font-size: 20px; font-weight: 600; }
    .notes-table { width: 100%; border-collapse: collapse; margin-top: 20px; }
    .notes-table th { text-align: left; padding: 12px; background: #0A0F1A; border-bottom: 1px solid #C9A84C30; font-size: 12px; text-transform: uppercase; letter-spacing: 1px; }
    .notes-table td { padding: 10px 12px; border-bottom: 1px solid #C9A84C10; font-family: monospace; }
    .note-row:hover { background: #C9A84C08; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #C9A84C20; text-align: center; color: #EEF2FF40; font-size: 12px; }
  </style>
</head>
<body>
  <div class="header">
    <h1 class="title">${instrumentData?.name || instrument.toUpperCase()} Part</h1>
    <p class="subtitle">Generated by Arco AI Music Studio</p>
  </div>
  
  <div class="info-grid">
    <div class="info-card">
      <div class="info-label">Key Signature</div>
      <div class="info-value">${convertedData.key}</div>
    </div>
    <div class="info-card">
      <div class="info-label">Tempo</div>
      <div class="info-value">${convertedData.tempo} BPM</div>
    </div>
    <div class="info-card">
      <div class="info-label">Time Signature</div>
      <div class="info-value">${convertedData.timeSignature[0]}/${convertedData.timeSignature[1]}</div>
    </div>
    <div class="info-card">
      <div class="info-label">Total Notes</div>
      <div class="info-value">${convertedData.notes.length}</div>
    </div>
  </div>
  
  <h3 style="color: #C9A84C; margin-bottom: 16px;">Note Details</h3>
  <table class="notes-table">
    <thead>
      <tr><th>#</th><th>Pitch</th><th>Note</th><th>Start (s)</th><th>Duration (s)</th><th>Velocity</th></tr>
    </thead>
    <tbody>
      ${convertedData.notes.map((note: any, idx: number) => {
        const noteName = noteNames[note.pitch % 12];
        const octave = Math.floor(note.pitch / 12) - 1;
        return `<tr class="note-row">
          <td>${idx + 1}</td>
          <td>${note.pitch}</td>
          <td><strong>${noteName}${octave}</strong></td>
          <td>${note.startTime.toFixed(2)}</td>
          <td>${(note.endTime - note.startTime).toFixed(2)}</td>
          <td>${note.velocity}</td>
        </tr>`;
      }).join('')}
    </tbody>
   </table>
  
  <div class="footer">
    <p>Arco Music Platform • AI-Powered Composition Tool</p>
  </div>
</body>
</html>`;
        
        zip.file(`${instrument}_part.html`, htmlContent);
        
        // Add MIDI file for each part
        const midiDataUri = generateMidiTrack(convertedData.notes, convertedData.tempo);
        const midiBlob = await fetch(midiDataUri).then(res => res.blob());
        zip.file(`${instrument}_part.mid`, midiBlob);
        
        // Add JSON data for each part
        const jsonContent = JSON.stringify({
          instrument: instrument,
          key: convertedData.key,
          tempo: convertedData.tempo,
          timeSignature: convertedData.timeSignature,
          notes: convertedData.notes,
          metadata: {
            generatedAt: new Date().toISOString(),
            sourceInstrument: midiData.instrument,
            originalNoteCount: midiData.notes.length
          }
        }, null, 2);
        
        zip.file(`${instrument}_data.json`, jsonContent);
      }
      
      const zipBlob = await zip.generateAsync({ type: 'blob' });
      const url = URL.createObjectURL(zipBlob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `band_arrangement_${Date.now()}.zip`;
      a.click();
      URL.revokeObjectURL(url);
    } catch (error) {
      console.error('Failed to generate band parts:', error);
    } finally {
      setIsGenerating(false);
    }
  };

  const toggleInstrument = (instrumentId: string) => {
    if (selectedInstruments.includes(instrumentId)) {
      setSelectedInstruments(selectedInstruments.filter(i => i !== instrumentId));
    } else {
      setSelectedInstruments([...selectedInstruments, instrumentId]);
    }
  };

  return (
    <div className="bg-gradient-to-br from-[#0A0F1A] to-[#05080F] rounded-2xl border border-[#C9A84C]/20 p-6">
      <div className="flex items-center gap-3 mb-6">
        <div className="w-10 h-10 rounded-xl bg-[#C9A84C]/10 flex items-center justify-center">
          <Users size={20} className="text-[#C9A84C]" />
        </div>
        <div>
          <h3 className="text-xl font-bold text-white">Band Arranger</h3>
          <p className="text-sm text-white/40">Generate individual parts for each instrument</p>
        </div>
      </div>
      
      <div className="grid grid-cols-2 md:grid-cols-3 gap-3 mb-6">
        {bandInstruments.map((instrument) => (
          <button
            key={instrument.id}
            onClick={() => toggleInstrument(instrument.id)}
            className={`flex items-center gap-3 p-3 rounded-xl transition-all duration-200 ${
              selectedInstruments.includes(instrument.id)
                ? 'bg-[#C9A84C]/20 border border-[#C9A84C]'
                : 'bg-white/5 border border-white/10 hover:border-[#C9A84C]/50'
            }`}
          >
            <span className="text-2xl">{instrument.icon}</span>
            <div className="flex-1 text-left">
              <div className="font-medium text-white text-sm">{instrument.name}</div>
              <div className="text-xs text-white/40">{instrument.range}</div>
            </div>
            {selectedInstruments.includes(instrument.id) && (
              <Check size={16} className="text-[#C9A84C]" />
            )}
          </button>
        ))}
      </div>
      
      <button
        onClick={generateParts}
        disabled={isGenerating || selectedInstruments.length === 0 || midiData.notes.length === 0}
        className="w-full flex items-center justify-center gap-2 py-3 bg-gradient-to-r from-[#C9A84C] to-[#E5C46B] text-[#05080F] rounded-xl font-semibold hover:shadow-lg hover:shadow-[#C9A84C]/25 transition-all duration-300 disabled:opacity-50 disabled:cursor-not-allowed"
      >
        {isGenerating ? (
          <>
            <Loader2 size={18} className="animate-spin" />
            Generating {selectedInstruments.length} Parts...
          </>
        ) : (
          <>
            <Download size={18} />
            Generate Band Parts ({selectedInstruments.length})
          </>
        )}
      </button>
      
      <p className="text-xs text-white/40 text-center mt-4">
        Each part includes HTML score, MIDI file, and JSON data
      </p>
    </div>
  );
}